name: Bug report
description: バグ報告用のテンプレート
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 何が起きたかを書いてください
      placeholder: 例：ログインできない
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: 確認事項
      options:
        - label: 最新版で再現する
          required: true
        - label: 既存Issueを検索した
          required: true
